export {default as OnboardingScreen } from './Onboarding/OnboardingScreen'
export {default as Login} from './AuthStack/LogIn/Login.jsx'
export {default as SignUp} from './AuthStack/SignUp/SignUp.jsx'
export {default as Home} from './MainStack/Home'
export {default as Details} from './MainStack/Details'
export {default as Search} from './MainStack/Search'
export {default as Profile} from './MainStack/Profile'
export {default as Chat} from './MainStack/Chat'
export {default as Friends} from './MainStack/Friends'
export {default as ChatUsers} from './MainStack/ChatUsers'