const actionType = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",

    SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_ERROR: "SIGN_UP_ERROR",

    GET_CURRENT_USER_REQUEST: "GET_CURRENT_USER_REQUEST",
    GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
    GET_CURRENT_USER_ERROR: "GET_CURRENT_USER_ERROR",

    GET_CURRENT_USER_CHATS: "GET_CURRENT_USER_CHATS"
}

export default actionType